### ISSUE TITLE
Crash saying "smarterfarmers requires moonlight" even after smarterfarmer was removed

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/SmarterFarmers#12]
I couldn't add smarterfarmers because it requires moonlight, something I couldn't find for the minecraft version I was using for my modpack, so I removed smarterfarmers. But the game still crashes on boot saying smarterfarmers requires moonlight.
It's not in the list anymore, the files aren't even in the folders anywhere.

**Comment by MehVahdJukaar** [comment]
This isn't useful at all. I need a latest.log. also use a launcher to install mods

**Comment by ghost** [comment]
I was using a launcher. And sorry I didn't provide a lot, I found that apparently moonlight was installed saying it wasn't. What helped was uninstalling moonlight and then reinstalling it and that worked, but so far I haven't gotten the smarterfarmers mod to work. Can't check it right now though.
