### ISSUE TITLE
Crash with possible incompatibility between smarter farmers and endless biomes

### ISSUE THREAD

**Issue by Avanstarwa** [MehVahdJukaar/SmarterFarmers#15]
I have replicatable crashes with this mod and Endless Biomes installed.
[crash-2024-03-02_14.59.54-server.txt](https://github.com/MehVahdJukaar/SmarterFarmers/files/14469645/crash-2024-03-02_14.59.54-server.txt)

Removing either mod fixes it.

**Comment by MehVahdJukaar** [comment]
their issue. that player can be null 
![image](https://github.com/MehVahdJukaar/SmarterFarmers/assets/24719182/dcccd405-2b32-4f48-8313-02590307c063)
